### ISSUE TITLE
Golden beetroot soup, golden mushroom stew, golden rabbit stew differ in effect from the original food

### ISSUE THREAD

**Issue by tankplanelaserkoala** [EndilCrafter/goldelight#1]
Game Version : 1.20.1

Forge version:47.2.20

GolDelight Version:1.0.7

Beetroot soup, mushroom stew, and rabbit stew provide a 'comfort' effect, but the golden fortified versions of these foods don't have these effects and have other effects. Add comfort to the Golden Enhancement version as well. If it's not what you intended, I'd appreciate it if you could add comfort to the golden enhanced version as well.

**Comment by EndilCrafter** [comment]
Thank you for pointing issue.
Beetroot soup belongs to Midas Hunger.
So I can't change other mod's effect.

I am rewriting mod's code.
Next update, I will add effects to them.
