### ISSUE TITLE
Not an issue, but I have a question

### ISSUE THREAD

**Issue by MikroChris** [EndilCrafter/goldelight#10]
How do I get the golden stem/hyphae? I can't find a way to get them :c

**Comment by EndilCrafter** [comment]
Plant golden fungus on FD's rich soil.
Then it will grow up like vanilla fungus.

**Comment by ssfwuu0721** [comment]
so... why can't it grow on golden soil?

**Comment by ssfwuu0721** [comment]
> Plant golden fungus on FD's rich soil. Then it will grow up like vanilla fungus.

so... why can't it grow on golden soil? like golden mushroom
