### ISSUE TITLE
Drinking golden cocoa does not remove harmful effects.

### ISSUE THREAD

**Issue by tankplanelaserkoala** [EndilCrafter/goldelight#7]
Please give it the ability to remove one harmful effect like the original cocoa.
![image](https://github.com/EndilCrafter/goldelight/assets/157739795/d9335489-bd5d-47d5-8f8b-40facd1fc054)

**Comment by EndilCrafter** [comment]
It is GD's standard. Removing harmful effects belongs to sheperds pie.
